---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stalwart.toando.de
  resources:
  - accounts
  - clusters
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stalwart.toando.de
  resources:
  - accounts/finalizers
  - clusters/finalizers
  - domains/finalizers
  verbs:
  - update
- apiGroups:
  - stalwart.toando.de
  resources:
  - accounts/status
  - clusters/status
  - domains/status
  verbs:
  - get
  - patch
  - update
